FROM nginx:1.19

ARG UID
EXPOSE $UID

RUN echo "Europe/Madrid" > /etc/timezone
RUN ln -s -f /usr/share/zoneinfo/Europe/Madrid /etc/localtime

RUN adduser -u ${UID} --disabled-password --gecos "" appuser

COPY default.conf /etc/nginx/conf.d/
COPY fullchain.pem /etc/nginx/fullchain.pem
COPY privkey.pem /etc/nginx/privkey.pem
COPY options-ssl-nginx.conf /etc/nginx/options-ssl-nginx.conf
COPY ssl-dhparams.pem /etc/nginx/ssl-dhparams.pem
